import type { LucideIcon } from "lucide-react"
import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BarChart2,
  Camera,
  Dumbbell,
  Bell,
  BookOpen,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronRight,
  Cloud,
  ClipboardList,
  Dna,
  Droplet,
  FileText,
  Flame,
  Folder,
  FlaskRound,
  Settings,
  Heart,
  HeartPulse,
  HelpCircle,
  Key,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  MessageCircle,
  Moon,
  Pill,
  Scissors,
  Search,
  Shield,
  Star,
  Square,
  Stethoscope,
  Sun,
  Target,
  Trash2,
  User,
  Users,
  Watch,
  X,
  Scale,
  Fish,
  Video,
} from "lucide-react"

const ICON_MAP: Record<string, LucideIcon> = {
  default: Star,
  cloud: Cloud,
  "☁︎": Cloud,
  "🔑": Key,
  "🌸": HeartPulse,
  "📅": CalendarDays,
  "🔥": Flame,
  "✍️": CheckCircle2,
  "💗": Heart,
  "💬": MessageCircle,
  "📄": FileText,
  "🩸": Droplet,
  "🎯": Target,
  "📋": ClipboardList,
  "🪶": Scissors,
  "🧪": FlaskRound,
  "⌚️": Watch,
  "📝": FileText,
  "🩺": Stethoscope,
  "🗂️": Folder,
  "📗": BookOpen,
  "💌": Mail,
  "🗑️": Trash2,
  "🔒": Lock,
  "📜": FileText,
  "✨": Star,
  "📚": BookOpen,
  "💡": Lightbulb,
  "🌙": Moon,
  "🌷": HeartPulse,
  "💊": Pill,
  "🧬": Dna,
  "🩷": HeartPulse,
  "🥗": Leaf,
  "💛": Heart,
  "❓": HelpCircle,
  "🔍": Search,
  "⚖️": Scale,
  "🏃": Activity,
  "🥱": Moon,
  "🏋️": Dumbbell,
  "☀️": Sun,
  "🐟": Fish,
  "🪨": Square,
  "✅": CheckCircle2,
  "✓": Check,
  "✕": X,
  "›": ChevronRight,
  "→": ArrowRight,
  "←": ArrowLeft,
  help: HelpCircle,
  doctor: Stethoscope,
  medication: Pill,
  checklist: ClipboardList,
  document: FileText,
  calendar: CalendarDays,
  community: Users,
  learn: BookOpen,
  health: HeartPulse,
  period: CalendarDays,
  flow: Droplet,
  labs: FlaskRound,
  profile: User,
  settings: Settings,
  insights: BarChart2,
  question: HelpCircle,
  video: Camera,
  photos: Camera,
  research: Search,
  provider: Stethoscope,
  goals: Target,
  notes: FileText,
  brief: FileText,
  icon: Star,
  defaultArrow: ChevronRight,
  regulate: CalendarDays,
  symptoms: HeartPulse,
  ttc: Target,
  understand: Search,
  weight: Scale,
  energy: Activity,
  sleep: Moon,
  pain: HeartPulse,
  moods: MessageCircle,
  discharge: Droplet,
  cravings: Leaf,
  digestion: Leaf,
  movement: Activity,
  meds: Pill,
  measurements: Scale,
  all: Users,
  newly: AlertTriangle,
  skin: HeartPulse,
  food: Leaf,
  wins: Star,
  vent: MessageCircle,
  comment: MessageCircle,
  messageCircle: MessageCircle,
}

export function MedicalIcon({
  name,
  size = 20,
  className,
  strokeWidth = 1.8,
}: {
  name: string
  size?: number
  className?: string
  strokeWidth?: number
}) {
  const Icon = ICON_MAP[name] ?? ICON_MAP.default
  return <Icon size={size} strokeWidth={strokeWidth} className={className} />
}
